export const projects = [
  {
    id:            "filmsort",
    slug:          "filmsort",
    title:         "FilmSort",
    subtitle:      "Offline-first Android media organizer",
    summary:
      "AI-powered Android app that parses messy filenames, fetches metadata via TMDB, and plays media offline.",
    caseStudy:     "filmsort",
    category:      "mobile",
    status:        "published",
    featured:      true,
    priority:      1,
    tags:          ["Android", "AI", "Offline-first", "Mobile"],
    techStack:     ["React Native", "Expo SDK 54", "AI Integrated", "Firebase", "API Services"],
    role:          "Film Media Manager",
    year:          2026,
    coverImageUrl: "/projects/filmsort-cover.png",
    galleryImageUrls: [],
    liveUrl:       "",
    githubUrl:     "",
  },

  {
    id:            "shazam",
    slug:          "shazam",
    title:         "SHAZAM",
    subtitle:      "AI design intelligence tool",
    summary:
      "Prompt-to-design tool powered by OpenRouter. Get color palettes, component ideas, and design system suggestions instantly.",
    category:      "ai-tool",
    status:        "published",
    featured:      true,
    priority:      2,
    tags:          ["AI", "Design", "OpenRouter", "UI/UX"],
    techStack:     ["Next.js", "TypeScript", "OpenRouter", "Tailwind CSS"],
    role:          "Creators | Newbie Devs",
    year:          2025,
    coverImageUrl: "/shazambanner.png",
    galleryImageUrls: ["/shazampj_bannercarousel2.jpeg", "/shazampj_bannercarousel3.jpeg"],
    liveUrl:       "https://shazam-ccbn.vercel.app/",
    githubUrl:     "https://github.com/react-timmy/shazam.git",
  },
  {
    id:            "buildoors",
    slug:          "buildoors",
    title:         "Buildoors",
    subtitle:      "Full-stack web project for builders",
    summary:
      "Full-stack platform for tracking projects and connecting with builders. React, Node.js, deployed on Railway.",
    category:      "web",
    status:        "published",
    featured:      true,
    priority:      3,
    tags:          ["Full-stack", "React", "Node.js", "MongoDB"],
    techStack:     ["React", "Node.js", "Express", "MongoDB"],
    role:          "Developers",
    year:          2025
    ,
    coverImageUrl: "/buildoorsbanner.png",
    galleryImageUrls: [],
    liveUrl:       "https://buildoors-rv8f.vercel.app/",
    githubUrl:     "https://github.com/react-timmy/buildoors.git",
  },
  {
    id:            "bless-network",
    slug:          "bless-network",
    title:         "Bless Network",
    subtitle:      "CLI deployment test — decentralised compute",
    summary:
      "Live deployment test of a client site on Bless Network's decentralised infrastructure using the BLS CLI. Brief to live node in under 2 Minutes.",
    category:      "client-work",
    status:        "published",
    featured:      true,
    priority:      4,
    tags:          ["Client Work", "Bless Network", "CLI", "Decentralised"],
    techStack:     ["Bless CLI", "BLS", "Next.js", "Decentralised Hosting"],
    role:          "CLI Testoors",
    year:          2025,
    coverImageUrl: "/blessnetworkpj_bannercarousel1.jpg",
    galleryImageUrls: ["/blessnetworkbannercarousel2.jpg"],
    liveUrl:       "https://plum-wallaby-cheri-wwyiwvd4.bls.dev/",
    githubUrl:     "",
  },
  {
    id:            "web3-community",
    slug:          "web3-community",
    title:         "Web3 Community Work",
    subtitle:      "Bless · Billions · Sentient AGI",
    summary:
      "Early contributor, content builder, and community amplifier across Bless Network, Billions Network, and Sentient AGI. Ran InfoFi campaigns, leaderboard efforts, and research commentary.",
    category:      "community",
    status:        "published",
    featured:      false,
    priority:      5,
    tags:          ["Web3", "Community", "AGI", "Content"],
    techStack:     ["Bless Network", "Billions Network", "Sentient AGI", "X / Twitter"],
    role:          "Contributor & Creator",
    year:          2024,
    coverImageUrl: "/projects/web3-cover.png",
    galleryImageUrls: [],
    liveUrl:       "",
    githubUrl:     "",
  },
];

export const featuredProjects = projects.filter((p) => p.featured && p.status === "published").sort((a, b) => a.priority - b.priority);
